name: 'sample_dbt_project'
version: '1.0.0'
config-version: 2

profile: 'default' # This profile name will be used in profiles.yml

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory for compiled artifacts
clean-targets:         # directories removed by `dbt clean`
  - "target"
  - "dbt_packages"
